### ISSUE TITLE
either license in the config file or integration license id must be specified

### ISSUE THREAD

**Issue by Utwo** [replicatedhq/replicated-sdk#119]
I started to get this error message in our testing cluster `either license in the config file or integration license id must be specified` on the replicated pod. I'm using ArgoCD for deploying the app helm chart. Replicated SDK ( 1.0.0-beta.12)  is installed as a dependency on that appchart.

**Comment by cbodonnell** [comment]
@Utwo do you know how exactly the chart is being installed with ArgoCD? Is the chart being pulled from the Replicated registry using credentials associated with a customer license? The error message indicates that the Replicated SDK did not have the necessary license context it needs to bootstrap.

You can run `helm get values <release-name> --all` and inspect the values under the `replicated` key. You should see the customer license that it was configured with there.

**Comment by Utwo** [comment]
It started working randomly without my intervention. So the trial license expired, I updated the expiration date on the replicated admin console but that was not reflected in my cluster. Even if I did a clean fresh install. I think the registry was still returning the old values. I will check again in 8 days. 

I will close this for now. Thank you!
